Improvement: wget to curl so proxies can be used for docker image building  (#1338)
amazeeio/lagoon pull request #1339
Opened 2019-10-24 03:45 UTC by duttonw

# Changelog Entry #1338 
Convert wget to curl calls so proxied systems can still build images

# Closing issues
closes #1338

2019-11-18 22:34 UTC, Schnitzel requested changes
@duttonw

Thanks for this, I think that's a good idea, just can we revert the changes where this is only used for internal requests (see my change requests). 
Thanks!

2019-11-18 22:34 UTC, Schnitzel commented on local-dev/api-data-watcher-pusher/api-watch-push.sh
> +    curl -s -L api:3000/graphql --header "Content-Type: application/json" --header "$bearer" --data "$json" --show-error
this will never use external proxies, please revert

2019-11-18 22:34 UTC, Schnitzel commented on services/ssh/authorize.sh
> +keys=$(curl curl -s -L $api/keys --header "Content-Type: application/json" --header "$bearer" --data "$data" --show-error)
this will never use external proxies, please revert

2019-11-18 22:34 UTC, Schnitzel commented on services/ssh/home/grant.sh
> +echo $(curl -s -L "$server/generate" --header "$header" --data "$data")
this will never use external proxies, please revert

2019-11-18 22:34 UTC, Schnitzel commented on services/ssh/home/token-debug.sh
> +token=$(curl -s -L "$server/generate" --header "$header" --data "$data" -d -v 2>&1)
this will never use external proxies, please revert

2019-11-18 22:34 UTC, Schnitzel commented on services/ssh/home/token-debug.sh
> +echo $(curl -s -L "$server/generate" --header "$header" --data "$data")
this will never use external proxies, please revert

2019-11-18 22:34 UTC, Schnitzel commented on services/ssh/home/token.sh
> +echo $(curl -s -L "$server/generate" --header "$header" --data "$data")
this will never use external proxies, please revert

2019-11-19 02:50 UTC, duttonw commented
> @duttonw
> 
> Thanks for this, I think that's a good idea, just can we revert the changes where this is only used for internal requests (see my change requests).
> Thanks!

Hi @Schnitzel ,

It should never go to the external proxy if the no_proxy settings is set correctly.  These could be reverted but I feel it is nicer to keep it all consistent with curl. Has the CICD pipeline been correct to get a passing build yet?

If you do want to keep it as wget for those internal internal requests i'm welcome to you pushing those changes onto this branch before merging.

2019-11-20 01:54 UTC, smlx commented
This PR replaces busybox wget calls in e.g. php images, and also GNU wget calls in e.g. node images. It seems unlikely that both these wget implementations have the same issue with proxies, so I wonder if the problem is a configuration issue instead?

Could you elaborate on the specific issue this PR solves?

2019-11-20 06:22 UTC, duttonw commented
Here's the issues that others have been having with wget alpine/busybox. If wget is replaced with gnu wget, then it would work better, but then thats a little bit bigger size then the busybox version. 

https://github.com/wurstmeister/kafka-docker/issues/487
https://gitlab.alpinelinux.org/alpine/aports/issues/10446
https://gitlab.com/gitlab-org/gitlab-ci-yml/merge_requests/197
https://unix.stackexchange.com/a/525474

2019-11-21 00:56 UTC, smlx commented
So the specific issue that this PR addresses is that wget is unable to access HTTPS through a HTTP proxy?

This bug was [fixed](http://lists.busybox.net/pipermail/busybox/2018-March/086282.html) in [busybox 1.29.0](https://www.busybox.net/). The earliest release of alpine with this version was [3.9](https://pkgs.alpinelinux.org/packages?name=busybox&branch=v3.9).

According to https://github.com/amazeeio/lagoon/issues/1324 only mariadb and varnish images use an old enough alpine to be affected by that bug. Is that where you were seeing the issue?

2019-11-21 01:10 UTC, duttonw commented
I'm still on the learning curve of containers and docker needing to work in a restricted network where the only way to communicate to the internet is via a proxy.

We have this problem with image amazeeio/python:2.7-ckan-v0.23.1 

which salsadigital built for us in ckan plugin https://github.com/qld-gov-au/ckanext-data-qld-theme/blob/develop/.docker/Dockerfile.ckan

from the looks of https://hub.docker.com/r/amazeeio/python/tags?page=1&name=ckan
would this issue go away if we change the version to tag 2.7-ckan-v1.1.4 ?

2019-11-21 01:55 UTC, smlx commented
That image does seem to be new enough:
```
$ docker run -it --rm  amazeeio/python:2.7-ckan-v0.23.1 -- cat /etc/alpine-release
3.9.4
```
And in fact https does seem to work through an http proxy:
```
$ docker run -it --rm --network host amazeeio/python:2.7-ckan-v0.23.1 -- sh -c 'all_proxy=127.0.0.1:8888 wget https://google.com -O-'
Connecting to google.com (172.217.167.110:443)
Connecting to www.google.com (172.217.167.100:443)
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en-AU">
...
```
Are you setting the relevant `all_proxy` environment variable as above?

2019-11-21 02:28 UTC, smlx commented
after some testing, busybox wget _does_ seem to work if you set `http_proxy`, but it has some issues with redirects via the proxy.. so curl is definitely a more robust solution :-)
sorry for the noise..

2019-11-21 05:03 UTC, duttonw commented
set http_proxy and https_proxy to http://externalip:3128 which is a squid3 proxy. wget to a https address in busybox image, the squid logs show it does not use connect and fails, which curl does correctly.

2020-02-06 02:21 UTC, smlx commented
@duttonw ping to see if you are able to address @Schnitzel's comments on this PR?

2020-02-06 02:56 UTC, duttonw commented
Hi @smlx , per https://github.com/amazeeio/lagoon/pull/1339#issuecomment-555308203 he has not responded if he still wants me to revert or keep them consistent as per my reply.

2020-02-06 03:04 UTC, smlx commented
ok, thanks. I missed this bit:
> If you do want to keep it as wget for those internal internal requests i'm welcome to you pushing those changes onto this branch before merging.

I might push some changes as per your comment :slightly_smiling_face:

2020-02-06 03:05 UTC, duttonw commented
just re-based due to conflicts. your welcome to pull in house and merge when happy :)

2020-09-03 17:46 UTC, closed without merging