140 mongo
amazeeio/lagoon pull request #158
Opened 2018-01-01 19:57 UTC by twardnw

2018-01-02 15:16 UTC, Schnitzel commented
Looks good, some changes:
- for the env variables we use a new feature of kubernetes 1.6 to import all keys from a configmap as env variables:
https://github.com/amazeeio/lagoon/blob/5da1856ba13eabd66df31d45a59c35cfdc4cafd3/images/oc-build-deploy-dind/openshift-templates/redis/template.yml#L73-L75
- is there a reason that we use the centos instead of alpine with mongo installed?

2018-01-02 15:16 UTC, Schnitzel requested changes
see comment :)

2018-01-03 19:12 UTC, twardnw commented
Well, same story as Varnish, there was a mongodb package hiding in APK Edge, have that added now, also updated to use the env var map too.

2018-01-04 00:37 UTC, Schnitzel requested changes

2018-01-04 00:37 UTC, Schnitzel commented on images/mongo/docker-entrypoint
> +exec "$@"
this is already defined in the main entrypoints.sh file:
https://github.com/amazeeio/lagoon/blob/master/images/commons/lagoon/entrypoints.sh#L15

so we don't need that file at all :)

2018-01-04 00:37 UTC, Schnitzel commented on images/mongo/yum.mongodb-org-3.4.repo
> +gpgkey=https://www.mongodb.org/static/pgp/server-3.4.asc
yum in alpine? :) 
guess we can remove that file.

2018-01-04 00:37 UTC, Schnitzel commented on images/oc-build-deploy-dind/openshift-templates/mongo/template.yml
> +    name: ${SERVICE_NAME}-persistent
we don't call the PVCs `-persistent ` anymore, as their name already suggests that they are persistent, just the `${SERVICE_NAME}`

2018-01-04 00:37 UTC, Schnitzel commented on images/oc-build-deploy-dind/openshift-templates/mongo/template.yml
> +              mountPath: ${PERSISTENT_STORAGE_PATH}
mongo has a predefined storage path, so it's not likely that a user wants to inject another path, let's define it hardcoded, see https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/openshift-templates/mariadb/template.yml#L89 as an example

2018-01-04 00:37 UTC, Schnitzel commented on images/oc-build-deploy-dind/openshift-templates/mongo/template.yml
> +parameters:
these seem not up to date, see https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/openshift-templates/mariadb/template.yml#L6 as an example

2018-01-04 19:36 UTC, Schnitzel approved these changes

2018-01-04 19:36 UTC, merged