Kubernetes typeDefs Revision alpha1 (WIP)
amazeeio/lagoon pull request #1582
Opened 2020-01-23 18:40 UTC by justinlevi

# Checklist
- [ ] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [ ] PR title is ready for changelog and subsystem label(s) applied

Explain the **details** for making this change. What existing problem does the pull request solve?

# Closing issues
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2020-01-23 19:17 UTC, rocketeerbkw requested changes

2020-01-23 19:17 UTC, rocketeerbkw commented on services/api/src/typeDefs.js
> +    targetName: String
remove openshiftProjectName. Add `displayName` which is non-globally unique (the current `name` field). Convert `name` field to be globally unique (unique key).

Openshift/K8s use the `name` (now unique) for projects/namespaces

2020-01-23 19:17 UTC, rocketeerbkw commented on services/api/src/typeDefs.js
> +    userCanSshToEnvironment(deploymentTargetName: String): Environment
`deploymentTargetName` > `name` assuming above unique name change is applied

2020-01-23 19:17 UTC, rocketeerbkw commented on services/api/src/typeDefs.js
> +    allDeploymentTargets: [Openshift | Kubernetes]
returns `DeploymentTarget` interface

2020-01-23 19:17 UTC, rocketeerbkw commented on services/api/src/typeDefs.js
> +    deploymentTarget: DeploymentTarget
deploymentTarget is id or name

2020-01-23 19:17 UTC, rocketeerbkw commented on services/api/src/typeDefs.js
> +  enum DeploymentTargets {
probably don't need enums at all

2020-01-23 19:17 UTC, rocketeerbkw commented on services/api/src/typeDefs.js
> +  type DeploymentTarget {
Is it useful to extend this type so that is returns projects

query {
 getDeployTarget {
    projects {
      id
     name, etc
   }
}

2020-01-23 20:29 UTC, justinlevi commented on services/api/src/typeDefs.js
> +    'lagoon_kubernetesBuildDeploy' | 'lagoon_openshiftBuildDeploy'
Is it still useful to have deploymentTargets separate from internal systems

2023-02-16 20:10 UTC, tobybellwood commented
The thinking here is long superseded!

2023-02-16 20:10 UTC, closed without merging