Added mongodb-tools to the base cli image
amazeeio/lagoon pull request #2117
Opened 2020-07-29 11:21 UTC by vincenzodnp

# Checklist
- [x] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [x] PR title is ready for changelog and subsystem label(s) applied

The PR aims to add the mongodb tools available for CLI base image, since it is the only way, for example, to import/export a MongoDB database.

# Changelog Entry
Lagoon is using "Release Drafter" to create changelogs using PR titles and labels

# Closing issues
closes #1718

2020-08-03 08:52 UTC, smlx commented
LGTM

2020-08-03 08:52 UTC, smlx approved these changes

2020-09-03 17:38 UTC, Schnitzel requested changes

2020-09-03 17:38 UTC, Schnitzel commented on images/php/cli/Dockerfile
> +	mongodb-tools \
```suggestion
       mongodb-tools \
```

2020-09-03 17:38 UTC, Schnitzel requested changes

2020-09-03 17:38 UTC, Schnitzel commented on images/php/cli/Dockerfile
> +       mongodb-tools \
```suggestion
        mongodb-tools \
```

2020-09-03 17:39 UTC, merged