Ignore the watchdog table for backups
amazeeio/lagoon pull request #2149
Opened 2020-08-13 02:37 UTC by smlx

# Checklist
- [x] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [x] PR title is ready for changelog and subsystem label(s) applied

Backups can fail for big tables. The table can be enormous and for lagoon will be unused since project will be using the `lagoon_logs` module. Not sure if this is really the best approach though, since `watchdog` might be used for something else in a non-drupal project.

# Closing issues
Closes: #2142

2020-08-13 03:14 UTC, seanhamlin requested changes
I think removing tables from backups breaks some assumptions about the backup system (i.e. that you can restore to a backup to fully roll your site back).

If we are to proceed with this, we should look to dump the structure of all tables, and then selectively look to dump the content of all the tables, depending on name.

2020-08-13 03:26 UTC, smlx commented
So something like this @seanhamlin ?
```
mysqldump --no-data ... > dump.sql
mysqldump --ignore-table=DB.watchdog ... >> dump.sql
```

2020-08-13 03:46 UTC, seanhamlin commented
As long as the second does not dump the structure again, e.g. with `mysqldump --no-create-info`, looks good to me.

2020-08-13 07:12 UTC, smlx commented
okay, I've tested the commands locally by dumping a table this way, restoring it into a new DB, and then diffing dumps of the two DBs.

2020-08-15 09:20 UTC, seanhamlin approved these changes
I can't see any valid reason in Lagoon when storing watchdog entries in the DB would be needed. Ideally the `dblog` module in Drupal would be disabled and Kibana used to search logs.

I especially like the multiline dump statements, which are far more readable in the first instance.

2020-09-03 17:52 UTC, Schnitzel commented
@smlx this is conflicting now, can you fix that one?

2020-09-04 02:59 UTC, smlx commented
@Schnitzel okay, conflicts fixed

2020-09-04 11:12 UTC, merged