Add new graphql to get customer by name
amazeeio/lagoon pull request #247
Opened 2018-02-15 23:13 UTC by igayoso

Create new graphql query to get customer by name.

2018-02-15 23:17 UTC, Schnitzel requested changes
just one tiny thing

2018-02-15 23:17 UTC, Schnitzel commented on services/api/src/schema.js
> +    customerByName(name: String!): Project
should be `Customer` no `Project`

2018-02-15 23:19 UTC, igayoso commented on services/api/src/schema.js
> +    customerByName(name: String!): Project
👍

2018-02-15 23:22 UTC, Schnitzel approved these changes
lets see what the CI says :)

2018-02-19 13:38 UTC, ryyppy commented
I will merge this in our #239 PR

2018-02-20 06:18 UTC, ryyppy commented
Added to #239 .. see https://github.com/amazeeio/lagoon/pull/239/commits/c91c422f80f66bbdd1f0d728de17508b2c60ed64

This can be closed now!

2018-02-20 17:30 UTC, closed without merging