Removing Billing Code from API
amazeeio/lagoon pull request #2837
Opened 2021-09-15 19:04 UTC by justinlevi

related:
* https://github.com/uselagoon/lagoon/pull/2614
* https://github.com/uselagoon/lagoon/pull/2688
* https://github.com/uselagoon/lagoon/pull/2794

# Checklist

- [x] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [x] PR title is ready for changelog and subsystem label(s) applied

This PR removes all billing related code from the API in favor of an external proprietary solution. 

# Closing issues

`closes #2687`

2021-09-16 18:27 UTC, justinlevi commented
@rocketeerbkw Could you take a look at this one?

2021-10-13 20:16 UTC, rocketeerbkw requested changes

2021-10-13 20:16 UTC, rocketeerbkw commented on node-packages/commons/src/tasks.ts
> -    }
This uptime robot data exists on the `openshift` field, I only remember discussing it being OK to remove from the billing group. Is it OK to remove here too?

2021-10-13 20:16 UTC, rocketeerbkw commented on services/api-db/docker-entrypoint-initdb.d/01-migrations.sql
> -CALL add_min_max_to_billing_modifier();
New installs won't get a `billing_modifier` table but are we also comfortable deleting existing ones? Could add a new migration to "drop if exists."

This could be a follow up ticket to leave data around "just in case."

2021-10-13 20:16 UTC, rocketeerbkw commented on services/api/src/models/group.ts
> +      | Group => ({
I think you can get rid of the OR `|` here too? `const groups = keycloakGroups.map((keycloakGroup: GroupRepresentation): Group => ({`

2021-10-13 20:16 UTC, rocketeerbkw commented on services/api/src/resolvers.js
>        }
Would you mind just getting rid of the `switch` and `return 'Group'`?

2021-10-13 20:16 UTC, rocketeerbkw commented on services/api/src/typeDefs.js
> +  type Group {
I think `Group` still needs to `implements GroupInterface` to avoid BC break.

2021-10-13 20:16 UTC, rocketeerbkw commented on services/keycloak/start.sh
> -    add_billing_modifier
Should we also add a function to delete the permissions/resources from keycloak? And write something to delete the billing groups that exist in keycloak?

This could be a follow up ticket to leave data around "just in case."

2022-01-26 12:59 UTC, rocketeerbkw approved these changes
Rebased on `main`, resolved change requests, tested against a prod dataset.

2022-01-26 20:39 UTC, merged