UI Get Projects resolver
amazeeio/lagoon pull request #3229
Opened 2022-07-26 11:37 UTC by timclifford

# Checklist

- [ ] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [ ] PR title is ready for inclusion in changelog

Explain the **details** for making this change. What existing problem does the pull request solve?

# Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2022-07-26 22:27 UTC, rocketeerbkw requested changes
I don't know much about the protocol mappers, so I have some questions about this method.

How often are they run? It's included in the token itself, so that means it only runs once on token creation? If it's run more often (like for every page load/query) how fast is it? Executing JS in Java isn't very performant. Our production tokens are valid for 10 hours, so any user<>project access changes won't be reflected until after 10 hours (the users token expired) or until the user manually logs out/logs in?

2022-07-26 22:27 UTC, rocketeerbkw commented on services/keycloak/startup-scripts/00-configure-lagoon.sh
> +    echo '{"protocol":"openid-connect","config":{"script":"var ArrayList = Java.type(\"java.util.ArrayList\");\nvar projects = new ArrayList();\nvar forEach = Array.prototype.forEach;\n\nforEach.call
This file is designed to be run as an init/update style (each function runs once, and in order). So each function, once released, should be considered "final" and not changed (misspellings aside).

The new mapper will need to be part of a new function (added at the end of the list) that should check if it has been run already.

2022-07-26 22:27 UTC, rocketeerbkw commented on services/api/src/typeDefs.js
> +    uiProjects(limit: Int, skip: Int): [Project]
I expect we'll have even more UI specific queries and mutations, should we put them under a new `ui` field now so we don't have to bc break anything later?

```graphql
{
  ui {
    projects(limit: 10, skip: 10)
  }
}
```

2022-08-01 16:09 UTC, timclifford commented
Thanks @rocketeerbkw - great points.

**How often will the projects mapper be run?**
- Every time the page is refreshed since a new access token is generated
- Or every 5mins without a page refresh since tokens are now refreshed server-side

This means that updating user projects on keycloak will only reflect in the ui when a new token is requested.

**How fast is it?**
- dashboard.amazeeio.cloud/projects - retrieves jwt in 40ms
- localhost (test with project mapper) - retrieves jwt in `150-200ms (has around 40 project ids attached)

So its around 4x-5x slower having to compute JS in Java. We could re-write the mapper in Java? 


**10h Production tokens**
Our production tokens are valid for 10 hours but after updating user attribute fields such as name, these changes were instantly reflected on a token refresh.

I also tested adding a test 'User Realm Role' protocol mapper to the 'lagoon-ui' client and refreshed the token on the UI which showed the update. So I think a token refresh will always retrieve the latest attribute on request rather than needing to re-authenticate or wait for expiry. With SSR now updating tokens every 5mins a user should only ever have outdated project id data for a maximum of 5minutes. 


**Other**
Also need to ensure we move the configuration logic for the new mapper to the end of the file, in a new function.

2022-08-02 01:58 UTC, smlx commented
Hey @timclifford FYI there is already a client which uses a built-in mapper to achieve what you're trying to do here - no need to inject JS or Java dynamic code. It was added in https://github.com/uselagoon/lagoon/pull/2941. Happy to show you how it works if you like :slightly_smiling_face:

2022-08-15 12:32 UTC, timclifford commented
> Hey @timclifford FYI there is already a client which uses a built-in mapper to achieve what you're trying to do here - no need to inject JS or Java dynamic code. It was added in #2941. Happy to show you how it works if you like 🙂

Thanks for showing me this, I've now updated the mapper to use the `group lagoon project IDs mapper`.

2023-02-16 21:03 UTC, tobybellwood commented
superseded by #3397

2023-02-16 21:03 UTC, closed without merging