Change: Update view permissions on Environment Variables
amazeeio/lagoon pull request #3406
Opened 2023-03-06 04:37 UTC by CGoodwin90

Addresses #3404 

- Updates the existing policies for viewing environment variables to cover guest level access. 
- Creates new scopes for viewing environment variable values -   `environment:viewValue:development`, `environment:viewValue:production` & `project:viewValue`
- Updates the resolver to check if value is requested and perform relevent permission checks

# Checklist

- [x] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [ ] PR title is ready for inclusion in changelog

# Closing issues

closes #3404

2023-03-06 05:30 UTC, tobybellwood commented
sidenote: We'll need to reflect these new permissions in the :scream: RBAC matrix in the docs...

2023-03-07 04:30 UTC, CGoodwin90 commented
> sidenote: We'll need to reflect these new permissions in the scream RBAC matrix in the docs...

Yep added them in - also tried to update the RBAC matrix to make it more readable, let me know if you think it works

2023-03-16 22:44 UTC, shreddedbacon commented on services/keycloak/startup-scripts/00-configure-lagoon.sh
> +  echo Recreating \"View Environment Variable for Development Environment\" permissions
Should move these echo statements from here to above the sections that the events take place, just so the logs reflect what is happening as they happen.

2023-03-23 02:50 UTC, shreddedbacon commented on services/api/src/resources/env-variables/resolvers.ts
Can you fix up the indentations in this file

2023-03-23 02:50 UTC, shreddedbacon requested changes
Only minor indentation fixes requested, once they're done all good

2023-03-23 04:14 UTC, shreddedbacon approved these changes

2023-03-23 05:49 UTC, merged