WIP: addProblems resolver
amazeeio/lagoon pull request #3422
Opened 2023-03-29 13:43 UTC by timclifford

We are missing a bulk addProblems resolver, add this ready for upcoming insights changes

2023-03-29 17:04 UTC, bomoko requested changes

2023-03-29 17:04 UTC, bomoko commented on services/api/src/typeDefs.js
> +    project: String
Does this project and environment that live at the root level of this input type do anything?
It looks like all the environment details are being determined by the environment ids that appear in the `AddProblemInput`?

It seems like it might be better to and a different input type, replacing `AddProblemInput` to something that had all the appropriate fields but _not_ the environment ID (or the source - more on that in a minute).

That way, you can rely solely on the `project` and `environment` that comes through at the top level - do a permissions check once AND have it resolve by name, rather than by ID.

2023-03-29 17:04 UTC, bomoko commented on services/api/src/resources/problem/resolvers.ts
> +  const environments = problems.reduce((environmentList, problem) => {
As mentioned in my other comment - if we rely on the top level project and environment details, we can get rid of this `reduce`

2023-03-29 17:04 UTC, bomoko commented on services/api/src/resources/problem/resolvers.ts
> +  for (let i = 0; i < environments.length; i++) {
This check could actually be done in the reduce - if you just check whether or not the environment has been added to "environmentList" or not, you could run the check there.

2023-03-29 17:04 UTC, bomoko commented on services/api/src/resources/problem/resolvers.ts
> +  const problemsArr = [];
So here's a question - what do we want to do if an entry already exists?

Initially I was thinking of adding the "addProblemsBySource" because what I was planning to do was just nuking the problems for the environment that were in the set of problems marked by that "source".
That way when a new Trivy scan came in, we wouldn't need to reconcile which problems were no longer there.

Actually, this might be something we want to chat a bit about.

2023-03-30 06:46 UTC, timclifford commented on services/api/src/typeDefs.js
> +    project: String
Yeah - I wanted to talk through the whole schema for problems since its been a while when we last put this together. But yeah, project isn't needed.

2023-03-30 06:49 UTC, timclifford commented on services/api/src/resources/problem/resolvers.ts
> +  const problemsArr = [];
This is the approach I took in the insights-handler, I delete all problems from source prior to adding new ones. Again though, something to discuss - this PR is currently to just get something up so I can point to this image to be able to add bulk problems

2023-11-23 21:32 UTC, tobybellwood commented
@bomoko to ensure this is still good to go!

2024-05-30 22:20 UTC, tobybellwood commented
@bomoko do we still need this with the way insights works?

2024-06-03 22:18 UTC, tobybellwood commented
CLosing pending problems/facts rewrite

2024-06-03 22:18 UTC, closed without merging