#609 #687 #688 - env vars in configmap and x-robots-tag on autogenerated routes
amazeeio/lagoon pull request #711
Opened 2018-10-25 04:09 UTC by twardnw

This solves tickets #609 #687 #688
#687 is adding the openshift name to the configmap
#688 is adding the autogenerated route names in a configmap
#609 sets the x-robots-tag header on autogenerated routes to prevent crawler indexing

2018-10-25 05:07 UTC, Schnitzel requested changes
overall super awesome work, thanks! Just some improvements :)

2018-10-25 05:07 UTC, Schnitzel commented on images/nginx/helpers/x-robots-header-development.conf
> +# Load environment variable LAGOON_ENVIRONMENT_TYPE into nginx variable. LAGOON_ENVIRONMENT_TYPE will be replaced via envplate during docker-entrypo
as LUA actually has access to the env variables itself, we could now load the env variables directly instead via the envplate system in the docker-entrypoint which is hard to understand.

be careful though with: https://stackoverflow.com/questions/41800071/unable-to-use-environment-variables-in-lua-code

2018-10-25 05:07 UTC, Schnitzel commented on images/nginx/helpers/x-robots-header-development.conf
> +  host = string.gsub(ngx.var.host, "%p", "%%%1")
can you document what this does?

2018-10-25 22:19 UTC, twardnw commented on images/nginx/helpers/x-robots-header-development.conf
> +  host = string.gsub(ngx.var.host, "%p", "%%%1")
👍🏻

2018-10-26 00:06 UTC, Schnitzel submitted a review, later dismissed

2018-11-06 16:24 UTC, Schnitzel requested changes

2018-11-06 16:24 UTC, Schnitzel commented on images/nginx/helpers/x-robots-header-development.conf
> +  -- escape characters in the hostname
can you describe which characters we are escaping?

2018-11-06 20:16 UTC, merged