841 disable git sha injection
amazeeio/lagoon pull request #879
Opened 2019-02-05 23:35 UTC by twardnw

# Checklist
- [x] Affected Issues have been mentioned in the Closing issues section
- [x] Documentation has been written/updated.
- [x] Changelog entry has been written

# Changelog Entry
## #841 
Change - disable the injection of the deployed SHA in the `LAGOON_GIT_SHA` environment variable. 
Adds - .lagoon.yml option `environment_variables.git_sha` to have the deployed SHA set.

# Closing issues
Closes #841

2019-02-07 14:45 UTC, Schnitzel commented
need to check: we would like to have still access to the SHA during build time

2019-02-19 23:36 UTC, twardnw commented
I suppose rather than checking for it in build-deploy.sh, we could set the value back to 0s when each service is deployed?

2019-02-22 16:21 UTC, Schnitzel requested changes

2019-02-22 16:21 UTC, Schnitzel commented on images/oc-build-deploy-dind/build-deploy.sh
> +  LAGOON_GIT_SHA="0000000000000000"
```suggestion
  LAGOON_GIT_SHA="0000000000000000000000000000000000000000"
```

2019-02-22 16:21 UTC, Schnitzel commented on tests/tests/features/disable-inject-git-sha.yaml
> +    expected_content: "LAGOON_GIT_SHA=0000000000000000"
```suggestion
    expected_content: "LAGOON_GIT_SHA=0000000000000000000000000000000000000000"
```

2019-02-27 21:22 UTC, merged