Ensure the searchguard init script is only run on initial deployment
amazeeio/lagoon pull request #908
Opened 2019-02-21 01:10 UTC by thom8

We have had a number of cases where the init script is run on a restart of the `logs-db` pod and resets the tenants to the default configuration.

This PR ensures that the searchguard init script `sgadmin_demo.sh` is only run on the initial deployment of `logs-db`.

You can also delete the state file and redeploy if you need to reset an existing deployment.

2019-02-21 01:28 UTC, Schnitzel commented
nice idea, but we need to make sure that this only runs on the very first node of an elasticsearch cluster. As in a cluster you have multiple nodes and all of them will run the same code, aka we would initialize the cluster the same amount that we have nodes. If we add a node to a cluster, it will also cause the cluster to be initialized again...

2019-02-21 01:28 UTC, Schnitzel requested changes
see comment above

2019-02-27 13:08 UTC, Schnitzel commented
interesting idea, though I'm not sure if this really solves our problem:
The current issue is that sometimes an ES node comes back into the cluster and is not fully synchronized yet with the rest of the cluster, because of that the script will run `sgadmin_demo.sh`.
With the new code the same could happen again: The ES node comes back into the cluster, is not fully synced, therefore the user `init` does not exist yet and it will start to initialize again.
Or maybe I'm missing something?

I would suggest to just remove the init code all together, and we document within the Setup Documentation of Lagoon that an admin needs to run `sgadmin_demo.sh` at the very very first time manually.

2019-04-03 22:09 UTC, thom8 commented
@Schnitzel removed the initialisation in `start.sh` and added docs for the initial setup.

2019-04-08 23:50 UTC, shreddedbacon reviewed
LGTM

2019-05-15 18:25 UTC, Schnitzel approved these changes

2019-05-15 18:25 UTC, merged